fix EnvironmentNotInitialized error
this missing retryOptions somehow caused the following crash on discord canary:
```
thread '<unnamed>' panicked at B:\b\discord_common\rust\napi\src\class.rs:139:37:
called `Result::unwrap()` on an `Err` value: EnvironmentNotInitialized
```
The default option for it is false, as per: https://github.com/OpenAsar/discord-desktop-datamining/compare/1552624...canary